var R=require("../../chunks/ssr/[turbopack]_runtime.js")("server/app/companies/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__0og59jf._.js")
R.c("server/chunks/ssr/node_modules_next_dist_1n3w9lb._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0opbbjh._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0j26pto._.js")
R.c("server/chunks/ssr/[root-of-the-server]__1rzsc_2._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0wpq8j3._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0symwr9.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0l_sp0x.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0q-w892.js")
R.c("server/chunks/ssr/apps_web__next-internal_server_app_companies_page_actions_1-jeh0h.js")
R.m(8059)
module.exports=R.m(8059).exports
